### ISSUE TITLE
Error: server/lib/index.js does not exist, can't deploy Firebase Functions

### ISSUE THREAD

**Issue by vinothpsv** [android/play-billing-samples#166]
When i try to deploy the firebase, i encounter this issue below issue 
Error: server/lib/index.js does not exist, can't deploy Firebase Functions

**Comment by calren** [comment]
@vinothpsv are you still facing this error? There have been some improvements made on the library since this issue was first filed, so I would give it another try. In the meantime, I'm going to go ahead and close this issue, but feel free to reopen another issue if you run into any other problems with the samples.

**Comment by vinothpsv** [comment]
Thanks @calren, let me re-try and post you an update
