### ISSUE TITLE
Request: allow to try sample without "google-services.json", to be able to test things without actually paying

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/play-billing-samples#171]
Currently we can't even try the sample:

![image](https://user-images.githubusercontent.com/5357526/50999571-23398b80-1533-11e9-8996-c2c0917dc0cf.png)

[ClassyTaxi.zip](https://github.com/googlesamples/android-play-billing/files/2747193/ClassyTaxi.zip)

**Comment by cartland** [comment]
Classy Taxi currently only compiles with a google-services.json from Firebase. The README for Classy Taxi explains how to set up the project.

The google-services.json file does not affect the Google Play Billing APIs. The google-services.json file is required in order to connect with the subscription management server. The current implementation uses Firebase Android APIs, and that is why the Android app needs the google-services.json.

The sample could be modified in order to compile without the google-services.json. One way could involve modifying the way Firebase is initialized. This blog post has more details:
https://firebase.googleblog.com/2017/03/take-control-of-your-firebase-init-on.html?m=1

Keep in mind that to avoid paying real money, you'll need to set up testing in the Google Play Console.
https://developer.android.com/google/play/billing/billing_testing

**Long term**: Classy Taxi could decouple the Android, server, and Firebase requirements so that each one can be run independently.

**Short term**: You can follow the instructions in the README in order to set up the Firebase project.

**Comment by AndroidDeveloperLB** [comment]
@cartland Why not add a debug mode to the API (maybe even in gradle), so that all of these will be possible out of the box, without the need to change each and every possible sample/POC (or the real project) ? 

It's really too bad that after so many years, it's still a very hard task to add IAP to a project, especially the way to test it.

It doesn't even let the developer himself pay inside his own app (credit card can't be the same).

**Comment by cartland** [comment]
Thanks for the feedback! You are describing two issues. One of them is related to the **sample code**, and is not related to Google Play Billing. The other issue is about **testing Google Play Billing**, and I think we have a solution.

### Sample code requires google-services.json
The sample code uses Firebase because Firebase Functions is the fastest, most reliable way that we know how to set up a server for an Android developer.

Adding a debug mode that doesn't require google-services.json would still require something similar to what I mentioned in my last comment. Even if someone completed that work, you still wouldn't get the benefits of the server implementation, which includes some of the most important features of managing subscriptions with Google Play Billing.

The Kotlin implementation of Trivial Drive [1] will show you how to use the Google Play Billing Library to buy subscriptions. That sample does not depend on a server, so you won't get any of the drawbacks of using the server implementation. You also won't get any of the benefits, and you will need to use the USE_FAKE_SERVER flag as described in the Classy Taxi README.

### Testing Google Play Billing without spending money
You can test Google Play Billing with any account, including your developer account. You need to set up testing in the Google Play Console for your test account [2]. Also, we improved subscription testing last year so that you can test subscription renewals in a matter of minutes, instead of days [3].


Based on these options, I think that following the README instructions will be the most valuable way to use this sample. If your app does not have a secure server, then you might want to use the Kotlin implementation of Trivial Drive instead of using Classy Taxi.

[1] https://github.com/googlesamples/android-play-billing/tree/3af7922cd0fddcaf8b76c8722a3d1d410d193576/TrivialDriveKotlin
[2] https://developer.android.com/google/play/billing/billing_testing
[3] https://android-developers.googleblog.com/2018/01/faster-renewals-for-test-subscriptions.html

**Comment by AndroidDeveloperLB** [comment]
It should work without the need of this extra file. 
About the ability to finally pay for my own product, finally. But how do I reset it to try again?

**Comment by calren** [comment]
We've [added](https://github.com/android/play-billing-samples/commit/bca6366a0bc34bf0ded661823fec8dd44c5468cf) a debug `google-services.json ` file , and this will allow you to build the app without firebase setup.

However, since the `google-services.json` is just a template, you'll still need to set up your own Firebase project with a real google-services.json file in order to see anything meaningful from the app.

**Comment by AndroidDeveloperLB** [comment]
The request is to be able to use the sample without this file, so that we can try it without any setup.
