### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by NarendraAndroidNGAGrpInc** [android/play-billing-samples#194]
Bundle ownedItems = InAppBillingService.getPurchases(3, mContext.getPackageName(),
                    itemType, continueToken) is throwing null pointer exception

**Comment by isaidamier** [comment]
Please point to the sample this bug applies. Also please add the Logcat output.

**Comment by pramodD** [comment]
Hi for me also facing this issue following is logs for this:
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Bundle com.android.vending.billing.IInAppBillingService.a(int, java.lang.String, java.lang.String, java.lang.String)' on a null object reference
       at com.myapp.purchaseutils.IabHelper.queryPurchases + 945(IabHelper.java:945)
       at com.myapp.purchaseutils.IabHelper.queryInventory + 624(IabHelper.java:624)
       at com.myapp.purchaseutils.IabHelper$2.run + 698(IabHelper.java:698)
       at java.lang.Thread.run + 818(Thread.java:818)

**Comment by calren** [comment]
@NarendraAndroidNGAGrpInc @pramodD It doesn't seem like this issue is specific to the sample apps in this repository, so I'll be closing this issue. If you feel like there's a bug in the billing library itself, feel free to file an issue [here](https://issuetracker.google.com/issues/new?component=311487&template=1014446) and we can take a closer look.
