### ISSUE TITLE
Re: setting a promo code to URL

### ISSUE THREAD

**Issue by yoursungjin** [android/play-billing-samples#207]
Under v2.0.1, is the following way of setting a promo code still valid?
https://developer.android.com/google/play/billing/billing_promo#generate_a_promo_url
If so, could you suggest some scenarios? 
Off the top of my head, I can't think of any scenario where you programmatically get a promo code and set it to the URL.

**Comment by yoursungjin** [comment]
Likewise, under v.2.0.1, is receiving PURCHASES_UPDATED still valid?
https://developer.android.com/google/play/billing/billing_testing#test-app-running

**Comment by calren** [comment]
Hey @yoursungjin , issues filed on this repo should ideally be related to the samples in this repo. Since this is a more generic question, I'm going to go ahead and close it for now. Feel free to ask questions on stackoverflow with the tag android-billing! That might get more traction and attention for generic Android billing issues than filing issues here. Thanks!
