### ISSUE TITLE
Subscription supports multiple user accounts on the same device

### ISSUE THREAD

**Issue by lixiaoyi** [android/play-billing-samples#212]
Hello team.

User uses an account to login into our application and purchase subscription will attach this subscription to his account.
If the user login with another account on the same device, and want to purchase a subscription for his account, it doesn't work, because the previous subscription is acknowledged and stay in the purchase, it cannot be purchased again.

Could you let us know this behaviour is by designed?
The same subscription product can only be purchased one time on the same device?

**Comment by calren** [comment]
Hey @lixiaoyi , issues filed on this repo should ideally be related to the samples in this repo. Since this is a more generic question, I'm going to go ahead and close it for now. Feel free to ask questions on stackoverflow with the tag android-billing! That might get more traction and attention for generic Android billing issues than filing issues here. Thanks!
