### ISSUE TITLE
BillingManager for Java >= 2.0 

### ISSUE THREAD

**Issue by bagintz** [android/play-billing-samples#214]
Are there plans to update the Java examples for the BillingManager?

**Comment by isaidamier** [comment]
Thanks for reporting this issue. We are tracking it.

**Comment by calren** [comment]
We currently don't have plans to update the Java examples, and decided to [deprecate](https://github.com/android/play-billing-samples/commit/b0ca34426ca7bddfbcb0557e195ea69898320440) them since they weren't using the latest library and we received feedback that having multiple samples was confusing for developers.

Feel free to check out our other billing library samples [TrivialDriveKotlin](https://github.com/android/play-billing-samples/tree/master/TrivialDriveKotlin) and [ClassyTaxi](https://github.com/android/play-billing-samples/tree/master/ClassyTaxi) and file an issue if you run into any problems with the samples or want to submit a feature request. 

If you run into any issues with the Billing library itself, you can also file a report [on our official issue tracker](https://issuetracker.google.com/issues/new?component=311487&template=1014446).
