### ISSUE TITLE
Why is the PurchaseState value of the JsonObject different from the numeric value of the defined State?

### ISSUE THREAD

**Issue by kdang-individual** [android/play-billing-samples#227]
PurchaseState value of Purchase object is defined as below.

> Purchase.java (package com.android.billingclient.api)
  @Retention(SOURCE)
  public @interface PurchaseState {
    // Purchase with unknown state.
    int UNSPECIFIED_STATE = 0;
    // Purchase is completed.
    int PURCHASED = 1;
    // Purchase is waiting for payment completion.
    int PENDING = 2;
  }
....
/** Returns the state of purchase. */
  public @PurchaseState int getPurchaseState() {
    switch (mParsedJson.optInt("purchaseState", PurchaseState.PURCHASED)) {
      case 4:
        return PurchaseState.PENDING;
      default:
        return PurchaseState.PURCHASED;
    }

Why is the PurchaseState value of the JsonObject different from the numeric value of the defined State?

**Comment by calren** [comment]
Hey @kdang-individual , issues filed on this repo should ideally be related to the samples in this repo. Since this is a more generic question, I'm going to go ahead and close it for now. 

That said, I agree this current state isn't very intuitive. and it could be worth filing an issue on the public tracker for the billing library here: https://issuetracker.google.com/issues/new?component=311487&template=1014446

Thanks for bringing this up!
