### ISSUE TITLE
querySkuDetailsAsync can't reach the callback

### ISSUE THREAD

**Issue by gmgunderground** [android/play-billing-samples#252]
I think to have followed all the steps correctly from the documentation but I can't reach the callback of querySkuDetailsAsync. The app is working correctly with IAB, now I'm only migrating from old library to the new 'com.android.billingclient:billing:2.0.3' but many problems.
Another question, in the new library is also necessary the use of License Key from Play Console? I don't find documentation about using that in the new library.

I can correctly and without errors reach this line `billingClient.querySkuDetailsAsync(params, (billingResult2, skuDetailsList) ->`

```
    private void setupIab()
    {
        billingClient = BillingClient.newBuilder(getApplicationContext()).enablePendingPurchases().setListener(this).build();
        billingClient.startConnection(new BillingClientStateListener()
        {
            @Override
            public void onBillingSetupFinished(BillingResult billingResult)
            {
                if (billingResult.getResponseCode() == BillingClient.BillingResponseCode.OK)
                {
                    List<String> skuList = new ArrayList<> ();
                    skuList.add("test_sku_1");
                    SkuDetailsParams params = SkuDetailsParams.newBuilder().setSkusList(skuList).setType(BillingClient.SkuType.INAPP).build();

                    billingClient.querySkuDetailsAsync(params, (billingResult2, skuDetailsList) ->
                    {
                        // Process the result.
                        if (billingResult2.getResponseCode() == BillingClient.BillingResponseCode.OK && skuDetailsList != null)
                        {
                        }
                    });

				}
            }

            @Override
            public void onBillingServiceDisconnected()
            {
                // Try to restart the connection on the next request to
                // Google Play by calling the startConnection() method.
            }
        });
    }
```

Best regards

**Comment by calren** [comment]
Hey @gmgunderground , I'm not quite sure what the issue you're describing is. Is it that you don't get the callback for `querySkuDetailsAsync` ? or that the condition `if (billingResult2.getResponseCode() == BillingClient.BillingResponseCode.OK && skuDetailsList != null)` is never reached?

if you think there's a potential issue with the billing library itself, you can file a bug [here](https://issuetracker.google.com/issues/new?component=311487&template=1014446) and the billing library engineering team can look into it further.

Since this isn't an issue regarding the samples itself, I'll go ahead and close this issue.
