### ISSUE TITLE
Google Play In-app Billing API version is less than 3

### ISSUE THREAD

**Issue by changcsw** [android/play-billing-samples#256]
I am using the implementation 'com.android.billingclient: billing: 2.0.3' version of Google payment api. It works fine on Google Play in the US, but when I switch to Google Play in Hong Kong, my app reports the 'Google Play In-app Billing API version is less than 3' error. I do n’t know how to solve it.

**Comment by calren** [comment]
The [Google Play Billing Library](https://developer.android.com/google/play/billing/billing_library_overview) (currently `2.0.3`) is the client API used in your Android app.
The [Google Play Developer API](https://developers.google.com/android-publisher) (currently `v3`) is the server API used for managing purchases and managing your app on Google Play.

The Google Play Developer API will only support the `v3` endpoint after 1 December, 2019. Here is the blog post:
https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html

If you have any additional questions about the API deprecation, please ask on Stack Overflow.

**Comment by changcsw** [comment]
We used Google Play Billing Library 2.0.3 in our app, and the same device and app on defferent network, when useing US VPN is normal, when useing Hong Kong the 'Google Play in-app Billing API version is less than 3' error, why? When there is error, how can the user avoid this error and pay normally ?

**Comment by LiuJCode** [comment]
> 我们在应用中使用了Google Play Billing Library 2.0.3，并且在不同的网络上使用了相同的设备和应用，使用US VPN正常，而在使用香港时，“ Google Play应用内计费API版本小于3”错误，为什么呢？出现错误时，用户如何避免该错误并正常付款？
Encountered the same problem as you, how did you solve it

**Comment by maclir** [comment]
But it seems like if you're not logged in on google play, this error is thrown even if you're on the latest version.

**Comment by liaoxsong** [comment]
> But it seems like if you're not logged in on google play, this error is thrown even if you're on the latest version.

That's also my issue here. This error message is misleading!

**Comment by wasiliysoft** [comment]
Has anyone solved this problem?  I faced a situation when a user cannot pay for an application for political reasons, I provided him with a free promotional code, he successfully activated it in the application store and now my application gives him exactly the same error as yours.  Any ideas how to solve this?

**Comment by Turnsole** [comment]
This issue is giving me a huge headache trying to support customers in Australia and Singapore. They're frequently unable to access purchasing despite having fairly new Android devices and valid Google Play accounts. "Google Play In-app Billing API version is less than 3" is a completely incorrect error code and wasted a lot of our time trying to debug the issue.

**Comment by claudioredi** [comment]
@Turnsole have you identified a root cause for this problem? The error description is totally misleading and I'm also having hard time identifying the issue as I cannot reproduce it locally unless I try on a simulator without any google account. 

Provided the amount of users having this issue im prod, it's impossible to be the same reason.
