### ISSUE TITLE
resultCode == BillingResponse.USER_CANCELED

### ISSUE THREAD

**Issue by JackieYang-PM** [android/play-billing-samples#258]
GPA.3390-0541-4284-99363
"The user successfully paid, but returned the result of the Liveme user cancellation, via the Google Play Billing API, error code=1
Liveme client calls GP payment interface "
![WechatIMG13423](https://user-images.githubusercontent.com/59216538/71431808-9c63cb80-270f-11ea-9bd2-e2d6e717d2b2.png)

**Comment by calren** [comment]
Hey @JackieYang-PM, it looks like you might be asking about a potential issue with the billing library itself, in which case you can file a bug [here](https://issuetracker.google.com/issues/new?component=311487&template=1014446) and the billing library engineer team can look into it more.

Since this isn't an issue regarding the samples itself, I'll go ahead and close this issue.
