### ISSUE TITLE
querySkuDetailsAsync is returning nill sku details

### ISSUE THREAD

**Issue by warmodroid** [android/play-billing-samples#259]
<img width="1078" alt="Screenshot 2019-12-26 at 9 56 49 PM" src="https://user-images.githubusercontent.com/16587828/71482834-acbc9900-282a-11ea-9c26-7a297a3a794f.png">
Please find the attached screenshot for more details.

**Comment by calren** [comment]
Hey @warmodroid, it looks like you might be asking about a potential issue with the billing library itself, in which case you can file a bug [here](https://issuetracker.google.com/issues/new?component=311487&template=1014446) and the billing library engineer team can look into it more.

Since this isn't an issue regarding the samples itself, I'll go ahead and close this issue.
