### ISSUE TITLE
DEVELOPER_ERROR and "Purchase not found for the given token" when acknowledge subscription product

### ISSUE THREAD

**Issue by lyw-94** [android/play-billing-samples#266]
Recently I found that there are some DEVELOPER_ERROR error in our online app, and the debug message is "Purchase not found for the given token", here are my code

`
AcknowledgePurchaseParams params =
AcknowledgePurchaseParams.newBuilder()
.setPurchaseToken(purchase.getPurchaseToken())
.setDeveloperPayload(developerPayload)
.build();

mBillingClient.acknowledgePurchase(params, listener);
`
And the purchase object is return from onPurchasesUpdated method, also i checked the user's purchaseToken , which is the same with i found in google play order management background.

so, what is the root cause of this problem? the order will refund in 3 days if we not acknowledge it, i'm so confused.

**Comment by calren** [comment]
@lyw-94 Were you able to check whether the purchase state is indeed `PURCHASED` before attempting to acknowledge it? Example [here](https://developer.android.com/google/play/billing/billing_library_overview#acknowledge). 

Since this is not an issue with any of the samples itself, I'm going to go ahead and close this issue. But if you think there might be a bug with the Play Billing library itself, you can go ahead and file an issue [here](https://issuetracker.google.com/issues/new?component=311487&template=1014446) and we can look into it more.

**Comment by lyw-94** [comment]
@calren  ok, i will try it, thanks!
