### ISSUE TITLE
consumeAsync method error

### ISSUE THREAD

**Issue by dddddl** [android/play-billing-samples#269]
When I call playStoreBillingClient? .QuerySkuDetailsAsync (params) method, the internal callback I getSkuDetails () failed. Response code: 6
Then when I call playStoreBillingClient? .ConsumeAsync (params) method, an internal callback occurred. An internal error occurred. I couldn't find the relevant solution, please help me

**Comment by calren** [comment]
Hey @dddddl  , issues filed on this repo should ideally be related to the samples in this repo. Since this is a more generic question, I'm going to go ahead and close it for now. Feel free to ask questions on stackoverflow with the tag android-billing! That might get more traction and attention for generic Android billing issues than filing issues here. Thanks!
