### ISSUE TITLE
Why is the default value of com.android.billingclient.api.Purchase.isAcknowledged() true?

### ISSUE THREAD

**Issue by zenanhu** [android/play-billing-samples#271]
`public boolean isAcknowledged() {
        return this.zzc.optBoolean("acknowledged", true);
 }`

**Comment by calren** [comment]
Hey @zenanhu , issues filed on this repo should ideally be related to the samples in this repo. Since this is a more generic question, I'm going to go ahead and close it for now. Feel free to ask questions on stackoverflow with the tag android-billing! That might get more traction and attention for generic Android billing issues than filing issues here. Thanks!
