### ISSUE TITLE
How can I handle the case of "Slow test card, declines after a few minutes"

### ISSUE THREAD

**Issue by yoonhok524** [android/play-billing-samples#272]
I am developing an Android app using Android Billing Library.
```
implementation 'com.android.billingclient:billing:2.1.0'
```

There are 4 test card options.

1. Slow test card, approves after a few minutes
2. Test card, always approves
3. Test card, always declines
4. Slow test card, declines after a few minutes

In the case of 1, "onPurchasesUpdated" callback method was called.
So I can handle it.

But in the case of 4, there is no response from the play store library.
"onPurchasesUpdated" callback was not called... (I waited more than 5 min...)

How can I handle case 4?
I can handle others.

**Comment by zenanhu** [comment]
I think "onPurchasesUpdated" is only called when a positive result happened. I didn't see any PurchaseState in contrast to PurchaseState.PENDING, which means there is not something like PurchaseState.PENDING_EXPIRED.

Here's my approach if you want to check if the previous pending transaction is expired.
Because the expiration duration is about 3 days for pending transaction, you should query purchases from Google Play Store using the Billing Library API to see if there's new completed transaction. So here you could get that the previous transaction is gone because it's expired.

**Comment by yoonhok524** [comment]
To know the purchase is canceled or not, I should use the function "consumeAsync()" provided by the library.

I tried to check using "queryPurchase()" function.
But I couldn't confirm that the purchase is declined or not...

Only I can confirm it using the "consumeAsync()" function...
When I call "consumeAsync()", the result is "BillingClient.BillingResponseCode.ITEM_NOT_OWNED".

It is very weird...

**Comment by calren** [comment]
Hey @yoonhok524 , thanks for reporting! I see that you've also filed an issue in our issue tracker: https://issuetracker.google.com/issues/149668311, so to avoid duplication, I'll go ahead and close this Github issue in favor of issuetracker

**Comment by zenanhu** [comment]
@yoonhok524 After the pending transaction is expired, "onPurchasesUpdated" is not called, so you don't need to handle this case. Just like this transaction never happened, user didn't pay and developer didn't grant entitlement.

**Comment by DonovanPhoenix** [comment]
I have the same issue. On launchBillingFlow you get a BillingResponseCode.ITEM_ALREADY_OWNED. the purchase returns PurchaseState.PENDING. If you consumeAsync immediately after its response is BillingResponseCode.DEVELOPER_ERROR, but after a few minutes (or whatever delay the transaction takes to fail) you can consumeAsync again then it returns BillingResponseCode.ITEM_NOT_OWNED, now you are allowed to retry the launchBillingFlow again. not complicated or misleading at all, good job google
