### ISSUE TITLE
purchase failed and result code is 6

### ISSUE THREAD

**Issue by lyw-94** [android/play-billing-samples#274]
in my app, there are many users occur this issue, they can query product details successfully but can't purchase, and google returns 6, sometimes the comsume process also get result code 6.

so what's the possible reason?

**Comment by calren** [comment]
Hey @zenanhu , issues filed on this repo should ideally be related to the samples in this repo. Since this is a more generic question, I'm going to go ahead and close it for now. Feel free to ask questions on stackoverflow with the tag android-billing! That might get more traction and attention for generic Android billing issues than filing issues here. Thanks!
