### ISSUE TITLE
Purchase failed Error ITEM_UNAVAILABLE (code: 4)

### ISSUE THREAD

**Issue by pencoba** [android/play-billing-samples#275]
Hi, I have already succeeded implemented Google Billing Library on my app. I can buy and consume a product.

Today I bought and consumed a product for about 3 times for testing purpose. Now I try again to purchase the same product I've got error message "The item you requested is not available for purchase". On Logcat the error code is ITEM_UNAVAILABLE (code: 4)

Any idea what could be the problem? and how to solve this?

**Comment by pencoba** [comment]
I don't know what the problem was but I have solved it by clear Play Store cache & data

**Comment by calren** [comment]
Hey @pencoba , issues filed on this repo should ideally be related to the samples in this repo. Since this is a more generic question, I'm going to go ahead and close it for now. Feel free to ask questions on stackoverflow with the tag android-billing! That might get more traction and attention for generic Android billing issues than filing issues here. 

If you think there might be an issue with the Play BIlling library itself, you can also file an issue [here](https://issuetracker.google.com/issues/new?component=311487&template=1014446)
