### ISSUE TITLE
Could not find SkuDetails to make purchase

### ISSUE THREAD

**Issue by gearsmotion789** [android/play-billing-samples#282]
I've been following all the steps in the instructions. However, whenever I try to tap on "Basic Plan" or "Premium Plan" on the app, the logcat just says "Could not find SkuDetails to make purchase". How can I get this to work?

**Comment by calren** [comment]
Hey @gearsmotion789 , this is usually an error that occurs when the subscription products haven't been set up in the Play Console correctly yet. 

A good thing to check is to see whether the app you uploaded to the Play Store has been published yet (it takes a while for the app to be published the first time). If the app is still in the 'pending' state, your app won't be able to query the Play Store for the subscription products.

I'm going to go ahead and close this issue since it seems to be a temporary set up problem, but feel free to keep commenting with issues you're facing and I'll continue answering the questions on this thread!

**Comment by thebeingapp** [comment]
Hi Calren,
Sorry that I am commenting on a closed issue. But this is something even I am facing.
And to your comment, one thing that I don't understand is, while the app could be in 'pending' state, but can't we simply test the subscription flow using the app installed directly from android studio? Which is what I am trying to do since yesterday. But logcat keeps throwing the error "Could not find SkuDetails to make purchase".

Could you please help here.

Thanks,

Abhishek
