### ISSUE TITLE
TrivialDriveKotlin: Subscription status should be updated when user cancel's subscription

### ISSUE THREAD

**Issue by elivity** [android/play-billing-samples#294]
Shouldn't there be a mechanism to delete the GoldStatus, when a subscription was canceled(when queryPurchases() returns an empty list)?

If you freshly subscribe, the flow is working well(storing GoldStatus(true) in the db), but there seems to be no mechanism to delete it, once a user is not eligable anymore(if the user canceled, and queryPurchases() returns an empty list)

Am I missing something?

Best Regards

**Comment by adhirajsinghchauhan** [comment]
I caught this issue during my own testing, and I think because this is mostly meant as a sample, the developer still has to be careful about the implementation.

I ended up handling this use-case myself (cancellations, refunds, revocations, etc.) similar to how you described it should be. A simple `localCacheBillingClient.clearAllTables()` works as intended.

**Comment by calren** [comment]
Good callout! This is definitely a buggy behavior in the sample. The ideal behavior would be to delete the subscription status once we find out the user is no longer subscribed.

**Comment by DAGalpin** [comment]
The sample has been updated to correctly handle subscription cancellation, as much as is possible from the client.
