### ISSUE TITLE
Why the User ID is scrambled in Firebase database?

### ISSUE THREAD

**Issue by vafaminato** [android/play-billing-samples#330]
1. I log into the app by my gmail account
2. I do some purchases by test card
3. I log into Firebase database and my user ID is some random letters
4. Even in google play console, I can just see the order ID and purchase token which doesn't show the user name as well.

This is important. Because if some client wants to get the refund, I don't know who did the purchase at the time. What is the solution?

**Comment by calren** [comment]
Hey @vafaminato , you're right in the sense that google play doesn't keep a record of the user associated with the purchase token. In order to issue refunds for clients, you should ask them for the order id that was attached in their purchase receipt. You can also search for purchases by the user's email and give the refund based on the email the used for the purchase.
