### ISSUE TITLE
TrivialDriveKotlin: Adding Account Hold/Restore before 1st November

### ISSUE THREAD

**Issue by chaoslorenz** [android/play-billing-samples#362]
From November 1st 2020,  Account & Hold is mandatory for any app that has a implementation of the Billing library that uses version 2+.  

Is this already implemented in TrivialDriveKotlin?

If not, can you please update TrivialDriveKotlin to match these requirements to help developers understand how to proceed with this.

Thank you,

**Comment by calren** [comment]
Since TrivialDriveKotlin doesn't rely on a server implementation and is getting the latest status of subscriptions with `queryPurchases()`, it is already handling account hold and restore.

**Comment by agGitHub** [comment]
> Since TrivialDriveKotlin doesn't rely on a server implementation and is getting the latest status of subscriptions with `queryPurchases()`, it is already handling account hold and restore.

Thanks for this clarification. Nevertheless, the doc says [here](https://developer.android.com/google/play/billing/subs#account-hold) : "When a user enters into account hold, you should leverage Real-time developer notifications to inform your user why access to the subscription was suspended. Within your app, you should provide a message with instructions on how to fix their payment method and regain access to the subscription. Your message should include a link to the Google Play subscription settings so that they can fix their payment method. "
Is it mandatory to display such a message ?
How can we do it ?
Thanks a lot.
