### ISSUE TITLE
Migration documentation from anjlab's library

### ISSUE THREAD

**Issue by MaxAndolini** [android/play-billing-samples#376]
Hi, I am using anjlab's library for subscriptions on the app. But it's terrible. When people cancel the subscription. It never informs us and Google told AIDL is deprecated.  I don't have good knowledge about these billing things. I need migration documentation from anjlab's library or any help Discord etc.

https://github.com/anjlab/android-inapp-billing-v3

**Comment by calren** [comment]
The library you linked was not supported by Google, so we unfortunately won't be able to provide migration guidance based on it.

**Comment by LordByron1788** [comment]
> The library you linked was not supported by Google, so we unfortunately won't be able to provide migration guidance based on it.

You don't even bother to adequately support the samples that Google does produce.

This is what happens when you don't understand the challenges that developers are facing and ignore people's requests.

So far you have no Java sample for this, and from what I can see from the posts on here, the Kotlin version is not even up to date.

Google are happy throw deadlines at developers asking them implement all sorts of billing logic. But that urgency is not matched when it comes to Google helping developers with these samples on this repo.

Really poor attitude.
