### ISSUE TITLE
Billing library 5 TAGs for offer and base plan

### ISSUE THREAD

**Issue by IsLery** [android/play-billing-samples#545]
Is that true that the offer inherits all the tags from the base plan and there's no way to remove them?
For example, I want to mark my base offer with "base" tag to distinguish it from other offers. But then the I receive the promotion offer with "base" tag in app though I haven't set it in the google play console.

Base plan tags
<img width="983" alt="image" src="https://user-images.githubusercontent.com/60115346/173225022-5c3977d2-2d0c-46e7-b5da-137e37e7a724.png">

Discount offer tags (but in app I get "base","upsale" and "yearly"
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/60115346/173225053-689265fd-4799-45fd-a719-430b8d40f986.png">

If this is a behavior by design please put it in the docs to prevent confusion.
Anyway it would be better to find some default plan by specific tag rather than filtering out all other tags.

**Comment by matale** [comment]
Yes this seems to be the case, the tags cascade downwards also you cant refer to the base plan by its name in code only the subscription name, the only option seems to be to filter by the offer tags like you said. Its very confusing if you try to do anything more complex then a simple subscription.

Depending on what you are trying to do it seems choosing the lowest price offer is the easiest thing to do, because the offers which the user doesn't qualify for disappear from the billing library response, so you can not guarantee a particular offer will be available to any user.

**Comment by IsLery** [comment]
Yes, looks like the inherited tags are the case - found a confirmation of it in a billing codelab. Only wish it was written explicitly in docs.
