### ISSUE TITLE
How to find Offertags & Baseplan ID which is shown in google play console?

### ISSUE THREAD

**Issue by axitasavani** [android/play-billing-samples#547]
Hi, I have added 1 Product ID: Monthly which has 2 base plans.
1. baseplan1m: offer1, offer2
2. baseplan6m: offer3, offer4

> Also they have their own offers.
> In GooglePlayConsole showing Ids like "baseplan1m", "offer10"and so on..
> How can I find it in the Billing response? 
> There is only showing `offertags[0:"baseplan6m", 1:"offer3"]` list which added tags in google play console... like, Below I have added 1 array of items.

`"subscriptionOfferDetails": [
    {
      "offerIdToken": "AUj/YhhzJar123UwYo/4ZmwI+Mfu6334qjYlCBOr7yAVi+XuVChWS2343413TSDFSW/pSDFGDFGASDm929LMZPOF5gioay8PLn13WeX5gQHi5uGXQbq504gqa2GgAXREFggavQ2dd3IAaQxtHw+w==",
      "pricingPhases": [
        {
          "priceAmountMicros": 630000000,
          "priceCurrencyCode": "INR",
          "formattedPrice": "₹630.00",
          "billingPeriod": "P6M",
          "recurrenceMode": 2,
          "billingCycleCount": 2
        },
        {
          "priceAmountMicros": 700000000,
          "priceCurrencyCode": "INR",
          "formattedPrice": "₹700.00",
          "billingPeriod": "P6M",
          "recurrenceMode": 1
        }
      ],
      "offerTags": [
        "baseplan6m",
        "offer3"
      ]
    }`

**Comment by matale** [comment]
Base plan ids and offer ids are not shown by billing library you cannot get these you can only get the subscription id, for everything else you need to use the tags.

When you add tags or generally make changes in the console they don't show up immediately in the billing library there is cache which causes a delay, you have to wait a few hours and/or clear the Google Play store data in your phone under settings -> Apps -> Find Google Play Store -> Storage -> Clear data.

Also note that offers the user doesn't qualify for will not be returned at all by Billing library, so if you have free trial offer which is set to "Never had a subscription" then once the user has signed up for any subscription with your app this offer will never show in the billing library response. There is no way to reset this as far as I can tell for testers which is a pain.

**Comment by axitasavani** [comment]
@matale  Hi, I have one more doubts: if I have added 2 tags in the same offer1 then how was the response? 
& How can I identify the base plan or offer plan item?

**Comment by matale** [comment]
All the tags of the offer and of the base plan will show in the offerTags for that offer so if you have 
Baseplan: tags: baseplan1m
    |--> Offers;
                   |---> offer1 tags: offer1, anotherTag 
                   |---> offer2 tags: offer2

The tags for offer1 will be offerTags ["baseplan1m", "offer1", "anotherTag"]
and for offer2 it will be  offerTags ["baseplan1m", "offer2"]
Because the offers inherit the tags from the base plan.
So you can find an offer by any unique tag on that offer, however remember there is no guarantee the offer will be there because the user has to qualify for the offer or it will not be returned by billing library.

As for finding a base plan it will also be included as an offer in the subscriptionOfferDetails (The base plan is returned as an offer by the billing library) it will only have its tags so  offerTags ["baseplan1m"] so you could look for offers with the baseplan1m tag only and no other tags to find a base plan.

However it might just be simpler to just create subscriptions with a single base plan so create different subscriptions for 1 month and 6 months each with only 1 base plan so you don't need to worry about finding the correct plan. 
https://stackoverflow.com/questions/72351253/google-play-billing-library-determine-base-plan-expiry-of-subscription-purcha/72673387#72673387

This also helps if you want to figure out which base plan was bought afterwards the Purchase object from queryPurchasesAsync does not contain the base plan that was bought only the product id so if you have multiple base plans there is no direct way of figuring out which plan was bought.
https://github.com/android/play-billing-samples/issues/538

**Comment by trambui09** [comment]
Thanks for the question, on the Play Billing Library side, we've added getOfferId() and getBasePlanId() methods to the SubscriptionOfferDetails object, check out https://developer.android.com/reference/com/android/billingclient/api/ProductDetails.SubscriptionOfferDetails for more details!
