### ISSUE TITLE
Where's the JAVA version of 'play-billing-codelab' example?

### ISSUE THREAD

**Issue by brunoaduarte** [android/play-billing-samples#577]
https://codelabs.developers.google.com/play-billing-codelab

**Comment by trambui09** [comment]
Hi Bruno, at Google I/O 2019, we announced that Android development will be increasingly Kotlin-first. For the Play Billing Codelab, we focused on creating a Kotlin version instead of a Java one. To learn more about our support approach to Android development tools and content, refer to this [announcement](https://developer.android.com/kotlin/first). I hope this helps!
