### ISSUE TITLE
billing V4 price problem

### ISSUE THREAD

**Issue by OhPeterPan** [android/play-billing-samples#605]
I am using billing v4. How can I configure a product that costs $0.99 for the first week and $3.99 for the next week? Please help me!!

**Comment by matale** [comment]
You should be able to do that with introductory price on v4 set the introductory price to 0.99 for 1 week then after that users will pay the full price, not sure exactly because the console is different now. If you use v5 you can set multiple pricing phases which might be more flexible.
See here for the old console steps https://help.magloft.com/en/articles/4841584-adding-free-trials-introductory-prices-to-your-subscription-in-google-play-console

**Comment by OhPeterPan** [comment]
> You should be able to do that with introductory price on v4 set the introductory price to 0.99 for 1 week then after that users will pay the full price, not sure exactly because the console is different now. If you use v5 you can set multiple pricing phases which might be more flexible. See here for the old console steps https://help.magloft.com/en/articles/4841584-adding-free-trials-introductory-prices-to-your-subscription-in-google-play-console

thank you，We are ready to upgrade V5
