### ISSUE TITLE
Android 14 UpsideDownCake: SecurityException RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED

### ISSUE THREAD

**Issue by Mercandj** [android/play-billing-samples#618]
Hello,

- Targeting and compiling on "UpsideDownCake" Revision 3
- Reproduced on device on Android 14 Beta 1 on Pixel 7 with gapps and google logged
    - [`Pixel 7 | panther_beta-upb1.230309.014-factory-4b84a328.zip`](https://developer.android.com/about/versions/14/download)
- Library version: `"com.android.billingclient:billing:5.2.0"`
- Crash when calling `BillingClient.startConnection`
- Stacktrace

```
FATAL EXCEPTION: main
Process: com.mercandalli.android.apps.sample, PID: 7785
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mercandalli.android.apps.sample/com.mercandalli.android.apps.sample.main_activity.MainActivity}: java.lang.SecurityException: com.mercandalli.android.apps.sample: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3773)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3913)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2436)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8180)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
Caused by: java.lang.SecurityException: com.mercandalli.android.apps.sample: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5372)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1851)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1791)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1779)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:754)
	at com.android.billingclient.api.zzn.zzc(com.android.billingclient:billing@@5.2.0:1)
	at com.android.billingclient.api.zzo.zze(com.android.billingclient:billing@@5.2.0:3)
	at com.android.billingclient.api.BillingClientImpl.startConnection(com.android.billingclient:billing@@5.2.0:36)
```

Thank you for your amazing job with PlayBilling. It's a great library 💪 🙏

**Comment by matale** [comment]
It looks like Android 14 is enforcing the new receiver requirements introduced in 13 but not enforced so best to stay bellow 14 for now until this lib catches up.

**Comment by Jinendra-Anchalia** [comment]
You can stay below android 14, I added the required flag -> receiverFlag = ContextCompat.RECEIVER_EXPORTED or receiverFlag = ContextCompat.RECEIVER_NOT_EXPORTED in ContextCompat.registerReceiver(context, br, filter, receiverFlags);

refer here https://developer.android.com/guide/components/broadcasts#context-registered-receivers

**Comment by drmrbrewer** [comment]
I'm seeing this too.  @Jinendra-Anchalia what do you mean by adding the required flag in this case, i.e. where the problem is happening with the `BillingClient.startConnection()` call... how is `ContextCompat.registerReceiver()` relevant in this situation?

**Comment by Jinendra-Anchalia** [comment]
@drmrbrewer as per the error logs above, somewhere in the code a broadcast is happening and android U puts restrictions on it, hence the REGISTER_RECEIVER() flag is needed. refer https://developer.android.com/guide/components/broadcasts#context-registered-receivers to validate

**Comment by drmrbrewer** [comment]
@Jinendra-Anchalia there is only one place in my entire code where I register a receiver with that method, and it has nothing to do with the billing library: 

`Intent intent = context.registerReceiver(null, new IntentFilter(Intent.ACTION_BATTERY_CHANGED));`

So I'm not sure what to change, or where?

**Comment by drmrbrewer** [comment]
@NLLAPPS OK thanks, slightly frustrating, but there we go.  I see that there is an [open issue here](https://issuetracker.google.com/issues/277822279), but there has been no update in two months.

**Comment by matale** [comment]
> You can stay below android 14, I simply added the required flag -> receiverFlag = ContextCompat.RECEIVER_EXPORTED or receiverFlag = ContextCompat.RECEIVER_NOT_EXPORTED in ContextCompat.registerReceiver(context, br, filter, receiverFlags);
> 
> refer here https://developer.android.com/guide/components/broadcasts#context-registered-receivers 

How did you add it when the error is in Googles library and not our code?

**Comment by ninh-huynh** [comment]
Finally !!!
https://developer.android.com/google/play/billing/release-notes#6-0-1

**Comment by Mercandj** [comment]
So great, thank you @ninh-huynh for the info of the fix, thank you all for the details.
And thks Google for the fix 💪 .

Closing this issue.

**Comment by ZouZLong** [comment]
I upgraded to the latest version of Google Billing System 6.0.1, but this problem still occurs "One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts"
Below is the detailed log:

17410-21 23:25:41.042 22825 22953 E AndroidRuntime: FATAL EXCEPTION: pool-6-thread-3
--
17510-21 23:25:41.042 22825 22953 E AndroidRuntime: Process: cellmate.qiui.com, PID: 22825
17610-21 23:25:41.042 22825 22953 E AndroidRuntime: java.lang.SecurityException: cellmate.qiui.com: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
17710-21 23:25:41.042 22825 22953 E AndroidRuntime: at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
17810-21 23:25:41.042 22825 22953 E AndroidRuntime: at android.os.Parcel.createException(Parcel.java:3041)
17910-21 23:25:41.042 22825 22953 E AndroidRuntime: at android.os.Parcel.readException(Parcel.java:3024)
18010-21 23:25:41.042 22825 22953 E AndroidRuntime: at android.os.Parcel.readException(Parcel.java:2966)
18110-21 23:25:41.042 22825 22953 E AndroidRuntime: at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
18210-21 23:25:41.042 22825 22953 E AndroidRuntime: at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
18310-21 23:25:41.042 22825 22953 E AndroidRuntime: at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
18410-21 23:25:41.042 22825 22953 E AndroidRuntime: at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
18510-21 23:25:41.042 22825 22953 E AndroidRuntime: at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
18610-21 23:25:41.042 22825 22953 E AndroidRuntime: at com.hyphenate.chat.core.EMAdvanceDebugManager.h(Unknown Source:21)
18710-21 23:25:41.042 22825 22953 E AndroidRuntime: at com.hyphenate.chat.core.EMAdvanceDebugManager.a(Unknown Source:4)
18810-21 23:25:41.042 22825 22953 E AndroidRuntime: at com.hyphenate.chat.EMClient.onNewLogin(Unknown Source:39)
18910-21 23:25:41.042 22825 22953 E AndroidRuntime: at com.hyphenate.chat.EMClient$8.run(Unknown Source:158)
19010-21 23:25:41.042 22825 22953 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
19110-21 23:25:41.042 22825 22953 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
19210-21 23:25:41.042 22825 22953 E AndroidRuntime: at java.lang.Thread.run(Thread.java:1012)
19310-21 23:25:41.042 22825 22953 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
19410-21 23:25:41.042 22825 22953 E AndroidRuntime: at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13908)
19510-21 23:25:41.042 22825 22953 E AndroidRuntime: at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
19610-21 23:25:41.042 22825 22953 E AndroidRuntime: at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
19710-21 23:25:41.042 22825 22953 E AndroidRuntime: at android.os.Binder.execTransactInternal(Binder.java:1339)
19810-21 23:25:41.042 22825 22953 E AndroidRuntime: at android.os.Binder.execTransact(Binder.java:1275)
19910-21 23:25:41.042 22825 22953 E AndroidRuntime:
20010-21 23:25:41.043 22825 22953 E CrashReport: Java Crash Happen cause by pool-6-thread-3(111)

**Comment by Prathap38** [comment]
Add ContextCompat.registerReceiver( this, mMessageReceiver, filter, ContextCompat.RECEIVER_EXPORTED )

It works for me
